### ISSUE TITLE
LED test script error

### ISSUE THREAD

**Issue by gauravhub** [hybridgroup/cylon-tessel#14]
I am trying to run LED sample program and followed following steps

$ cylon generate tessel my-tessel-project
$ cd my-tessel-project
$ npm install
$ tessel run blink.js

TESSEL! Connected to TM-00-04-f000da30-005d4f38-34942586.
INFO Bundling directory <project directory path>
INFO Deploying bundle (18.10 MB)...
INFO Running script...
/app/node_modules/cylon/lib/lodash.js:33: attempt to index upvalue 'vr' (a nil v
alue)

**Comment by stewart** [comment]
Hi @gauravhub - apologies for the issue. The minifier is obscuring it a bit, but this is caused by this underlying issue in Tessel's runtime: https://github.com/tessel/runtime/issues/682.

We're trying to figure out a band-aid fix for now, and will get back to you when we have one.

**Comment by stewart** [comment]
I've pushed a branch that removes the lo-dash build from Cylon, which seems to correct the issue at hand.

You can add it to `my-tessel-project` with the following command:

    $ npm install git://github.com/hybridgroup/cylon.git#tessel

And then run your script (`tessel run blink.js`) again.

Please let me know if this fixes your problem.

**Comment by gauravhub** [comment]
Thanks @stewart...I am able run the LED script sample now

**Comment by deadprogram** [comment]
Looks like this issue was resolved. Closing.
